version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: task-printer-mcp-server
    environment:
      - DB_PATH=/app/data/job_queue.db
      - PORT=3001
    volumes:
      - ./data:/app/data
      - ./shared:/app/shared:ro
    ports:
      - "3001:3001"
    restart: unless-stopped